% filenames and folders
filenames = {'exp_1_interleaved_incomplete',...
             'exp_2_block_incomplete',...
             'exp_3_block_complete',...
             'exp_4_block_complete_simple',...
             'exp_5_block_complete_mixed',...
             'exp_6_block_complete_mixed_2s',...
             'exp_7_block_complete_mixed_2s_deactivate',...
             'exp_8_block_complete_mixed_2s_amb',...
             'exp_9_incentives'};

%filenames = {'evoutcome'};
folder = 'data/behavior/reformat/';

data = readtable([folder, filenames{5}])

data(:, 'cfout') == 1