exp_num = 1;
sess = 0;

param = load(...
    sprintf('data/midpoints_ED_exp_%d_%d_mle.mat',...
    round(exp_num), sess ...
    ));

nll1 = param.nll;

param = load(...
    sprintf('data/midpoints_ED_exp_%d_%d_mle2.mat',...
    round(exp_num), sess ...
    ));

nll2 = param.nll;